# This is a sample render.yaml file for deploying both the backend and frontend
# to Render.com. You can use this as a template for your deployment.

services:
  # Backend API Service
  - type: web
    name: neural-nostalgia-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false # This means you'll need to enter it manually in the Render dashboard
      - key: REPLICATE_API_KEY
        sync: false # This means you'll need to enter it manually in the Render dashboard
    
  # Frontend Static Site
  - type: web
    name: neural-nostalgia-frontend
    env: static
    buildCommand: echo "No build required for static site"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
